workflows:
  ios-build:
    name: iOS Kingston Build
    max_build_duration: 60
    environment:
      node: 20.6.1
      ruby: 3.3.0
      xcode: 16.4
    cache:
      cocoapods: true
      npm: true
    scripts:
      - name: Install Node dependencies
        script: npm ci
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install
      - name: Build iOS app and export IPA
        script: |
          cd ios
          xcodebuild clean -workspace Kingston.xcworkspace -scheme Kingston -configuration Release
          xcodebuild -workspace Kingston.xcworkspace -scheme Kingston -configuration Release -sdk iphoneos \
            -archivePath $PWD/build/Kingston.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/build/Kingston.xcarchive \
            -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
    artifacts:
      - ios/build/Kingston.ipa
      - ios/build/Kingston.xcarchive






