cache_paths:
  - ~/.npm
  - ~/.cocoapods
  - ios/Pods
  - ios/build

workflows:
  ios-build:
    name: Build iOS app
    environment:
      ruby: 3.3.6
      xcode: latest
      cocoapods: default
      vars:
        NODE_ENV: development

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Setup CocoaPods
        script: |
          gem install cocoapods

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build & Export
        script: |
          cd ios
          xcodebuild clean -workspace Kingston.xcworkspace -scheme Kingston -configuration Release
          xcodebuild -workspace Kingston.xcworkspace -scheme Kingston -configuration Release -sdk iphoneos \
            -archivePath $PWD/build/Kingston.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/build/Kingston.xcarchive \
            -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
    artifacts:
      - ios/build/*.ipa








