# .codemagic.yaml for unsigned IPA export
workflows:
  ios-build-unsigned:
    name: Build Unsigned IPA for Kingston (Capacitor React)
    max_build_duration: 30
    environment:
      node: latest
      ruby: default
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build React app
        script: |
          npm run build

      - name: Sync Capacitor and install CocoaPods
        script: |
          npx cap sync ios
          cd ios/App
          pod install

      - name: Build unsigned Xcode archive
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme App -configuration Release \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            -archivePath $PWD/build/App.xcarchive archive

      - name: Export unsigned IPA file
        script: |
          cd ios/App
          cat <<EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>release-testing</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
            <key>teamID</key>
            <string>Y36C79F763</string>
            <key>thinning</key>
            <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF
          
                    xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive \
                      -exportOptionsPlist exportOptions.plist -exportPath $PWD/build \
                      CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

    artifacts:
      - ios/App/build/*.ipa
    publishing:
      email:
        recipients:
          - anirudhiyer2009@gmail.com
        notify:
          success: true
          failure: true





