workflows:
  ios-build:
    name: Build iOS app (Capacitor React)
    environment:
      node: latest
      ruby: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Node dependencies
        script: npm ci
      - name: Build React web app
        script: npm run build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Build iOS app archive
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme App -configuration Release
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos \
            -archivePath $PWD/build/App.xcarchive archive
      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ../exportOptions.plist \
            -exportPath $PWD/build
    artifacts:
      - ios/App/build/*.ipa
    publishing:
      email:
        recipients:
          - anirudhiyer2009@gmail.com






