workflows:
  ios-build-unsigned:
    name: Build Unsigned IPA for Kingston (Capacitor React)
    max_build_duration: 30
    environment:
      node: latest
      ruby: default
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build React app
        script: |
          npm run build

      - name: Sync Capacitor and install CocoaPods
        script: |
          npx cap sync ios
          cd ios/App
          pod install

      - name: Build unsigned Xcode archive
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme App -configuration Release \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            -archivePath $PWD/build/App.xcarchive archive

      - name: Copy .app folder as artifact
        script: |
          mkdir -p ios/App/build/app_folder
          cp -R ios/App/build/App.xcarchive/Products/Applications/App.app ios/App/build/app_folder/

      # Optional: Keep your export unsigned IPA step (may fail without signing)
      
    artifacts:
      - ios/App/build/app_folder/App.app/**   # <- your downloaded .app folder here    





