workflows:
  ios-build:
    name: Build iOS app (Capacitor React, unsigned)
    max_build_duration: 30
    environment:
      node: latest
      ruby: default
      xcode: latest
    scripts:
      - name: Install Node dependencies
        script: |
          npm ci

      - name: Build React web app
        script: |
          npm run build

      - name: Sync Capacitor and install pods
        script: |
          npx cap sync ios
          cd ios/App

          # Manually create Podfile if not generated
          if [ ! -f Podfile ]; then
            echo "platform :ios, '13.0'" > Podfile
            echo "use_frameworks!" >> Podfile
            echo "target 'App' do" >> Podfile
            echo "  pod 'Capacitor'" >> Podfile
            echo "  pod 'CapacitorCordova'" >> Podfile
            echo "end" >> Podfile
          fi

          pod install

      - name: Build iOS archive (unsigned)
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme App -configuration Release \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            -archivePath $PWD/build/App.xcarchive archive

      - name: Export unsigned IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ../exportOptions.plist -exportPath $PWD/build \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

    artifacts:
      - ios/App/build/*.ipa




