workflows:
  ios-build:
    name: iOS Kingston Build
    max_build_duration: 60
    environment:
      node: latest
      ruby: latest
      cocoapods_cache_enabled: true
      flutter: none
      xcode: latest
      vars:
        NODE_ENV: development
    scripts:
      - name: Install node dependencies
        script: npm install
      - name: Install pods
        script: |
          cd ios
          pod repo update
          pod install
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild \
            -workspace Kingston.xcworkspace \
            -scheme Kingston \
            -configuration Debug \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/build/Build/Products/Debug-iphoneos/Kingston.app
      - ios/build/Build/Products/Debug-iphoneos/Kingston.ipa






