workflows:
  react-native-ios-free-dev:
    name: Build iOS (Manual Signing, Free Dev Account)
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push

    scripts:
      - name: Install Node dependencies
        script: npm install

      - name: Install CocoaPods dependencies
         script: |
             cd ios
          pod install --verbose || (cat Podfile.lock && exit 1)
              cd ..

      - name: Build iOS Debug .app (no codesign)
        script: |
          cd ios
          xcodebuild \
            -workspace Kingston.xcworkspace \
            -scheme Kingston \
            -configuration Debug \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            BUILD_DIR=build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO


