workflows:
  ios-build:
    name: Build iOS app
    environment:
      vars:
        NODE_ENV: development
      ruby: 3.3.6
      xcode: latest
      cocoapods: default
      flutter: none
      cache:
        # Only cache default folders
        - ~/.npm
        - ~/.cocoapods
    scripts:
      - name: Install Node dependencies
        script: npm ci
      - name: Setup Ruby and install CocoaPods
        script: |
          rbenv global 3.3.6
          gem install cocoapods
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS app and export IPA
        script: |
          cd ios
          xcodebuild clean -workspace Kingston.xcworkspace -scheme Kingston -configuration Release
          xcodebuild -workspace Kingston.xcworkspace -scheme Kingston -configuration Release -sdk iphoneos \
            -archivePath $PWD/build/Kingston.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/build/Kingston.xcarchive \
            -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
    artifacts:
      - ios/build/*.ipa




