workflows:
  react-native-ios-free-dev:
    name: Build iOS (Manual Signing, Free Dev Account)
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "Kingston"
        BUNDLE_ID: "com.anirudh.kingston"
        APPLE_ID: "anirudhiyer2009@gmail.com"
        TEAM_ID: "Y36C79F763"
      node: latest
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Install Node dependencies (root)
        script: |
          npm install

      - name: Install CocoaPods dependencies (ios)
        script: |
          cd ios
          pod install --verbose
          cd ..

      - name: Build iOS Debug .app (no codesign)
        script: |
          cd ios
          xcodebuild \
            -workspace Kingston.xcworkspace \
            -scheme Kingston \
            -configuration Debug \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            BUILD_DIR=build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/build/Debug-iphoneos/*.app




