workflows:
  unsigned-ipa-build:
    name: Build unsigned iOS IPA
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_NAME: "Kingston"
      xcode: latest
      cocoapods: default
      ruby: 3.3.6
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npx cap sync ios
      - name: Build iOS project
        script: |
          cd ios
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $PWD/build/App.xcarchive CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
    artifacts:
      - ios/build/*.ipa







