platform :ios, '12.0'

require_relative '../node_modules/react-native/scripts/autolink-ios'

target 'Kingston' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'KingstonTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
