platform :ios, '12.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'  # If this file exists in your RN version

target 'Kingston' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'KingstonTests' do
    inherit! :complete
  end

  use_flipper!({ 'Flipper' => '0.125.0' })

  post_install do |installer|
    react_native_post_install(installer)
  end
end
